### ISSUE TITLE
Features brainstorm for 1.3b

### ISSUE THREAD

**Issue by yucongkoo** [AY2324S1-CS2103T-W16-2/tp#141]
1. duplicate person detection update(not by name but by phone or email maybe?) (garret)
1. easy-to-detect flags detection (case-sensitiveness) (Garrett)
1. output box display update, make formatting better and wrap around to prevent horizontal scrolling. (jiufong)
1. Change way of displaying optional parameters. (jiufong)
1. negative index error handling. (Joshua)
1. error handling stardardization(do we want to inform users a command did not change anything? What should we do if there are multiple inputs that cause errors?) (yucong)
1. Update DG to mention not-in-scopes.

**Comment by LamJiuFong** [comment]
1. Empty optional fields : "-"
