### ISSUE TITLE
[PE-D][Tester B] Help command produces the wrong user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W16-2/tp#252]
![Screenshot 2023-11-03 at 4.20.48 PM.png](https://raw.githubusercontent.com/Cleon2/ped/main/files/4f8b08e8-e20f-441e-9e68-90c2a75be235.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Cleon2/ped#2

**Comment by yucongkoo** [comment]
Duplicate bug of #248
