### ISSUE TITLE
[PE-D][Tester E] Unclear find command guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W16-2/tp#263]
![image.png](https://raw.githubusercontent.com/ketweeen/ped/main/files/42d36209-ce59-4383-85aa-4bfe88a419c7.png)

What prefixes can work with the find is not specified. It implies that this command can work for all prefixes but there are some prefixes that does not work with this (e.g. at/, dt/, etc.)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: ketweeen/ped#1

**Comment by TehOPanas** [comment]
The prefixes that can be used are specified at the features section
