### ISSUE TITLE
[PE-D][Tester C] Editable fields for each customer

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W16-2/tp#266]
![image.png](https://raw.githubusercontent.com/cmHuang777/ped/main/files/4b8084f7-803f-4ab7-8749-4aad551b6085.png)

While it is mentioned in the user guide that we cannot edit people to have the same number or email, it is not explained why, and why we can have two people with the same name and same address.
While unlikely, some people may still share the same email address just like how people may be living in the same house. So I don't get why people can have the same address but not the same email. (eg your customers are elderly and the email is handled by their children who happened to be your customer too)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: cmHuang777/ped#5

**Comment by yucongkoo** [comment]
Assigning @TehOPanas as this is an issue of identifying duplicate persons.

My suggestions is to include a section at the start of UG on our definition of same persons, alongside with a short rationale.

**Comment by TehOPanas** [comment]
For the same name and same address, I think we can argue from the point that, the address input can be very general, like postal code, or area the customer live in, it is not limited to specific household or so on, that is why we allow it to happen
