### ISSUE TITLE
[PE-D][Tester E] Duplicate prefixes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W16-2/tp#267]
t/ is used twice, which may caused confusion for future iterations.

![Screenshot 2023-11-03 at 16.50.04.png](https://raw.githubusercontent.com/ketweeen/ped/main/files/d82adbad-f627-481a-876d-bc5fc28f12fd.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: ketweeen/ped#2

**Comment by yucongkoo** [comment]
@Jweewee what do you think about this? I believe currently the only thing we can do is to include in the UG mentioning that these `t/` are different prefixes when used in different commands.
