### ISSUE TITLE
[PE-D][Tester A] No input limit to email

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W16-2/tp#274]
![Screenshot 2023-11-03 170352.png](https://raw.githubusercontent.com/Choonyan02/ped/main/files/81bfd58b-fb09-455a-a4a1-d555e38a1d06.png)

A small issue; I just noticed that there is a character limit for most fields except for email.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Choonyan02/ped#9

**Comment by yucongkoo** [comment]
I think this can be rejected as it will not cause any error in our UI, such extreme inputs need not be handled as according to project constraints
