### ISSUE TITLE
[PE-D][Tester D] Formatting of the UG is bugged

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W16-2/tp#277]
![image.png](https://raw.githubusercontent.com/dishenggg/ped/main/files/1c40a617-67ef-4afb-981f-6052c8424e16.png)

All sections after the list command is indented by 1 level

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: dishenggg/ped#4

**Comment by yucongkoo** [comment]
Problem already fixed
